[project]
name = "ai_engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv",
    "pydantic",
    "jinja2",
    "litellm",
    "guardrails-ai",
]
